//         ERROR HANDLING
//try-catch blocks
        // try{
        //     ...normal code
        // }catch(err){
        //     // err is error object
        //     ...handling error
        // }
let a = 5;
let b = 6;
console.log("a = " ,a);
console.log("b = ",b);
console.log("a+b = ", a+b);


 try{
    console.log("a+b = ", a+c);        /// error
        }catch(err){
            // err is error object
           console.log(err);
        }
console.log("a+b = ", a+b);
console.log("a+b = ", a+b);
console.log("a+b = ", a+b);
console.log("a+b = ", a+b);
console.log("a+b = ", a+b);